routes/web.php
<?php

Route::get('/', function () {
    return redirect(admin_vw() . '/login');
});


Route::get('/reset-password', function () {
    return 'Reset password successfully';
});

Auth::routes(); //['verify' => true]

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::get('/user/verify_page', 'Auth\RegisterController@verifyingPage');


Route::group(['prefix' => 'admin'], function () {

    Route::get('login', 'Auth\Admin\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Auth\Admin\LoginController@loginAdmin')->name('admin.auth.login');


    //admin password reset routes
    //https://academy.muva.tech/blog/part-viii-admin-password-reset-in-our-multiple-authentication-system-for-laravel-5-4/
    Route::post('/password/email', 'Auth\Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\Admin\ResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

    Route::get('/', 'HomeController@index');
    Route::get('dashboard', 'HomeController@index')->name('admin.index');

    Route::group(['middleware' => 'auth:admin'], function () {

//
//        foreach (\App\Models\Permission::all() as $permission) {
//            if ($permission->type == 'get')
//                Route::get('/' . $permission->alias . '/' . $permission->name, ['middleware' => 'permission:' . $permission->name, 'uses' => $permission->controller_name . '@' . $permission->function_name]);
//            if ($permission->type == 'post')
//                Route::post('/' . $permission->alias . '/' . $permission->name, ['middleware' => 'permission:' . $permission->name, 'uses' => $permission->controller_name . '@' . $permission->function_name]);
//            if ($permission->type == 'put')
//                Route::put('/' . $permission->alias . '/' . $permission->name, ['middleware' => 'permission:' . $permission->name, 'uses' => $permission->controller_name . '@' . $permission->function_name]);
//            if ($permission->type == 'delete')
//                Route::delete('/' . $permission->alias . '/' . $permission->name, ['middleware' => 'permission:' . $permission->name, 'uses' => $permission->controller_name . '@' . $permission->function_name]);
//        }

        Route::get('users-home', 'HomeController@getUsers');

        Route::group(['prefix' => 'role'], function () {
//            Route::get('roles', 'RoleController@roles');
//            Route::get('add-role', 'RoleController@addRole');
//            Route::post('add-role', 'RoleController@postAddRole');
//            Route::get('edit-role/{id}', 'RoleController@editRole');
//            Route::put('edit-role/{id}', 'RoleController@putRole');
//            Route::delete('delete-role/{id}', 'RoleController@delete');
            Route::get('role-data', 'RoleController@roleData');
//            Route::get('addPermission', 'PermissionController@addPermission');
//            Route::get('add-permission-role/{role_id}', 'PermissionController@permissions');
//            Route::get('add-permission-role/{role_id}', 'PermissionController@addPermission');
//            Route::get('add-permission-role/{role_id}', 'PermissionController@addPermissionRole');

            Route::get('permission-role/{role_id}', 'PermissionController@getPermissionRole');
            Route::post('add-role-permissions/{role_id}', 'PermissionController@postAddRolePermissions');

        });

        Route::group(['prefix' => 'manage'], function () {
            Route::get('admins', 'Admin\AdminController@index')->name('admin.admins.index');
            Route::get('admin-data', 'Admin\AdminController@anyData');
            Route::get('admin/{id}/edit', 'Admin\AdminController@edit');
            Route::put('admin/{id}', 'Admin\AdminController@update');
            Route::get('admin/create', 'Admin\AdminController@create');
            Route::post('admin', 'Admin\AdminController@store');
            Route::delete('admin/{id}', 'Admin\AdminController@delete');
//            Route::post('admin/export', 'AdminController@export');
            Route::put('admin-activation', 'Admin\AdminController@adminActivate');

            Route::get('users', 'Admin\UserController@index')->name('admin.users.index');
            Route::get('user-data', 'Admin\UserController@anyData');
            Route::get('user-details/{id}', 'Admin\UserController@userDetails');
//            Route::put('verify-email', 'UserController@verifyEmail');
            Route::put('user-activation', 'Admin\UserController@userActive');
            Route::put('user-league', 'Admin\UserController@userHasLeague');
//            Route::post('user/export', 'UserController@export');

        });

        Route::resource('teams', 'Admin\TeamController');
        Route::group(['prefix' => 'team'], function () {
            Route::get('team-data', 'Admin\TeamController@anyData');
            Route::put('activation', 'Admin\TeamController@teamActivate');
        });

//////////Sport/////////////////////////////////
        Route::resource('sports', 'Admin\SportController');
        Route::post('sports/upload-media/{id}/', 'Admin\SportController@upload_media');
        Route::delete('sports/remove-media/{id}/', 'Admin\SportController@remove_media');

        Route::group(['prefix' => 'sport'], function () {
            Route::get('sports-data', 'Admin\SportController@anyData');
            Route::put('activation', 'Admin\SportController@activation');
            Route::post('/{id}', 'Admin\SportController@update');

        });
 /////////////////////////////League/////////////
        ///
         Route::resource('leagues', 'Admin\LeagueController');
        Route::group(['prefix' => 'league'], function () {
            Route::get('league-data', 'Admin\LeagueController@anyData');
            Route::put('activation', 'Admin\LeagueController@activation');

        });
///////////////////Constants///
        Route::get('constant', 'Admin\ConstantController@index')->name('constants.index');

        Route::group(['prefix' => 'constant'], function () {

            Route::resource('payments', 'Admin\PaymentController');
            Route::get('payment/payment-data', 'Admin\PaymentController@anyData');

            Route::resource('awards', 'Admin\AwardController');
            Route::get('award/award-data', 'Admin\AwardController@anyData');

            Route::resource('cities', 'Admin\CityController');
            Route::get('city/city-data', 'Admin\CityController@anyData');

            /////FacilityGround
            Route::resource('facilityGrounds', 'Admin\FacilityGroundController');
            Route::get('facilityGround/ground-data', 'Admin\FacilityGroundController@anyData');


            /////FacilitySize
            Route::resource('facilitySizes', 'Admin\FacilitySizeController');
            Route::get('facilitySize/size-data', 'Admin\FacilitySizeController@anyData');


//            Route::get('setting/settings', 'SettingController@getSettings');
            Route::get('setting/setting-data', 'SettingController@anyData');
//            Route::get('setting/{id}/edit', 'SettingController@edit');
//            Route::put('setting/{id}/edit', 'SettingController@update');
//            Route::get('setting/create', 'SettingController@create');
//            Route::post('setting/create', 'SettingController@store');
//            Route::post('setting/export', 'SettingController@export');
//            Route::delete('setting/{id}', 'SettingController@delete');

        });


//        Route::post('addPermission', 'PermissionController@postAddPermission');

        Route::post('logout', 'Auth\Admin\LoginController@logout')->name('admin.logout');

    });
});

app/Http/Controllers/Admin/ConstantController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
//use App\Repositories\Eloquents\ConstantEloquent;

class ConstantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $constant;

    public function __construct()
    {
     //   $this->constant = $constantEloquent;
        view()->share(['main_title' => 'Constants management']);

    }
    public function index()
    {
        //
        $data = [
            'sub_title' => 'constant',
            'icon' => 'icon-leagues',
        ];
        return view(admin_constants_vw().'.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/constants/awards.blade.php
@extends(admin_layout_vw().'.index')
@section('css')

@endsection
@section('content')

    <div class="m-portlet__body">
        <div class="m-grid__item m-grid__item--fluid m-wrapper" style="background-color:white;padding-top: 50px;">


            <div class="m-content" >
                <div class="portlet-body table-responsive">
                    <table class="table table-striped table-bordered table-hover table-checkable order-column"
                           id="awards_tbl">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Title(En)</th>
                            <th>Title(Ar)</th>
                            <th>action</th>
                        </tr>
                        </thead>

                    </table>
                </div>

            </div>
        </div>

    </div>

@endsection
@section('js')
    <script src="{{url('/')}}/assets/js/awards.js" type="text/javascript"></script>
@stop

resources/views/admin/constants/cities.blade.php
@extends(admin_layout_vw().'.index')
@section('css')
    <style>
        .m-content{
            padding-top:50px;
        }
        .categBox {
            height: 150px;
            width: 100%;
            display: table;
            transition:.5s all

        }
        .col-md-4{
            padding:10px 30px  !important;
        }

        .categ-text {
            color:white;
            font-size: 1.5rem;
            font-weight: 600;
            display: table-cell;
            vertical-align: middle;
            text-align: center;

        }
        .categLink:hover{
            text-decoration: none;
        }

    </style>
@endsection
@section('content')
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">

        </div>
        <div class="m-portlet__head-tools text-right" style="margin-bottom:25px;">

            <a href="{{route('cities.create')}}" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air add-city-mdl" >
                            <span>
                                <i class="fa fa-plus"></i>
                                <span>New City</span>
                            </span>
            </a>

        </div>

    </div>
    <div class="m-portlet__body">
        <div class="m-grid__item m-grid__item--fluid m-wrapper" style="background-color:white;padding-top: 50px;">


            <div class="m-content" >
                <div class="portlet-body table-responsive">
                    <table class="table table-striped table-bordered table-hover table-checkable order-column"
                           id="cities_tbl">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name(En)</th>
                            <th>Name(Ar)</th>

                            <th>action</th>
                        </tr>
                        </thead>

                    </table>
                </div>

            </div>
        </div>

    </div>

@endsection
@section('js')
    <script src="{{url('/')}}/assets/js/cities.js" type="text/javascript"></script>
@stop

resources/views/admin/constants/index.blade.php
@extends(admin_layout_vw().'.index')
@section('css')
    <style>
        .m-content{
            padding-top:50px;
        }
        .categBox {
            height: 150px;
            width: 100%;
            display: table;
            transition:.5s all

        }
        .col-md-4{
            padding:10px 30px  !important;
        }

        .categ-text {
            color:white;
            font-size: 1.5rem;
            font-weight: 600;
            display: table-cell;
            vertical-align: middle;
            text-align: center;

        }
        .categLink:hover{
            text-decoration: none;
        }

    </style>
@endsection
@section('content')

    <div class="m-portlet__body">
        <div class="m-grid__item m-grid__item--fluid m-wrapper" style="background-color:white;padding-top: 50px;">


            <div class="m-content" >
                <div class="row">
                    <div class="col-md-4">
                        <a href="{{route('payments.index')}}" class="categLink">
                            <div class="categBox m--bg-brand">
                                <h4 class="categ-text">Payment Method</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="{{route('awards.index')}}" class="categLink">
                            <div class="categBox m--bg-info">
                                <h4 class="categ-text">Awards</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="{{route('cities.index')}}" class="categLink">
                            <div class="categBox m--bg-danger">
                                <h4 class="categ-text">Cities</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="{{route('facilityGrounds.index')}}" class="categLink">
                            <div class="categBox m--bg-success ">
                                <h4 class="categ-text">Facility Grant </h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="{{route('facilitySizes.index')}}" class="categLink">
                            <div class="categBox m--bg-accent">
                                <h4 class="categ-text">Facility Size</h4>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="introduction.html" class="categLink">
                            <div class="categBox m--bg-warning">
                                <h4 class="categ-text">Instructions</h4>
                            </div>
                        </a>
                    </div>

                </div>

            </div>
        </div>

    </div>

@endsection
@section('js')

@stop

resources/views/admin/constants/payments.blade.php
@extends(admin_layout_vw().'.index')
@section('css')
    <style>
        .m-content{
            padding-top:50px;
        }
        .categBox {
            height: 150px;
            width: 100%;
            display: table;
            transition:.5s all

        }
        .col-md-4{
            padding:10px 30px  !important;
        }

        .categ-text {
            color:white;
            font-size: 1.5rem;
            font-weight: 600;
            display: table-cell;
            vertical-align: middle;
            text-align: center;

        }
        .categLink:hover{
            text-decoration: none;
        }

    </style>
@endsection
@section('content')

    <div class="m-portlet__body">
        <div class="m-grid__item m-grid__item--fluid m-wrapper" style="background-color:white;padding-top: 50px;">


            <div class="m-content" >
                <div class="portlet-body table-responsive">
                    <table class="table table-striped table-bordered table-hover table-checkable order-column"
                           id="payments_tbl">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Title(En)</th>
                            <th>Title(Ar)</th>
                            <th>Type</th>
                            <th>action</th>
                        </tr>
                        </thead>

                    </table>
                </div>

            </div>
        </div>

    </div>

@endsection
@section('js')
    <script src="{{url('/')}}/assets/js/payments.js" type="text/javascript"></script>
@stop

resources/views/admin/constants/schedules.blade.php
@extends(admin_layout_vw().'.index')

@section('css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{url('/')}}/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css"/>
    <link href="{{url('/')}}/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css"
          rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="{{url('/')}}/assets/global/css/components-md.min.css" rel="stylesheet" id="style_components"
          type="text/css"/>
    <link href="{{url('/')}}/assets/global/css/plugins-md.min.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME GLOBAL STYLES -->
@endsection
@section('content')

    <div class="row">

        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="fa fa-search font-dark"></i>
                        <span class="caption-subject bold uppercase"> Filter </span>
                    </div>

                </div>
                <div class="portlet-body">
                    <div class="table-container">
                        {!! Form::open(['method'=>'POST','url'=>url(admin_constant_url().'/schedule/export')]) !!}

                        <table class="table table-striped table-bordered table-hover table-checkable"
                               id="datatable_products">
                            <thead>
                            <tr role="row" class="heading">
                                <th width="1%">
                                </th>

                                <th width="10%"> Title</th>
                                <th width="20%"> Type</th>
                                <th width="10%"> Language</th>
                                <th width="10%"> Action</th>
                            </tr>
                            <tr role="row" class="filter">
                                <td></td>
                                <td>
                                    <input type="text" class="form-control form-filter input-md" name="title"
                                           placeholder="Title" id="title">

                                </td>
                                <td>
                                    <select class="form-control input-md type select2" name="type" id="type"
                                            data-placeholder="Choose Type">
                                        <option value="">Choose Type</option>
                                        <option value="food">Food</option>
                                        <option value="exercise">Exercise</option>
                                    </select>
                                </td>
                                <td>
                                    <select class="form-control input-md lang_id select2" name="lang_id" id="language_id"
                                            data-placeholder="Choose Language">
                                        <option value="">Choose Language</option>
                                        @foreach($languages as $language)
                                            <option value="{{$language->id}}">{{$language->name}}</option>
                                        @endforeach
                                    </select>
                                </td>
                                <td>
                                    <div class="margin-bottom-5">
                                        <a href="javascript:;"
                                           class="btn btn-sm btn-success btn-circle btn-icon-only filter-submit margin-bottom"
                                           title="Search">
                                            <i class="fa fa-search"></i>
                                        </a>

                                        <a href="javascript:;"
                                           class="btn btn-sm btn-danger btn-circle btn-icon-only filter-cancel"
                                           title="Empty">
                                            <i class="fa fa-times"></i>
                                        </a>
                                        <button type="submit"
                                                class="btn btn-sm btn-default btn-circle btn-icon-only filter-export margin-bottom"
                                                title="Export">
                                            <i class="fa fa-file-excel-o"></i>
                                        </button>
                                    </div>

                                </td>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="{{$icon}} font-dark"></i>
                        <span class="caption-subject bold uppercase"> {{$sub_title}}</span>
                    </div>
                    <div class="actions">
                        <a href="{{url(admin_constant_url().'/schedule/create')}}" class="btn btn-circle btn-info add-schedule-mdl">
                            <i class="fa fa-plus"></i>
                            <span class="hidden-xs"> Add New </span>
                        </a>
                    </div>

                </div>


                <div class="portlet-body">

                    <table class="table table-striped table-bordered table-hover table-checkable order-column"
                           id="schedules_tbl">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th> Title</th>
                            <th> Time</th>
                            <th> Type</th>
                            <th> Language</th>
                            <th> Action</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

@endsection

@section('js')

    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{{url('/')}}/assets/global/scripts/datatable.js" type="text/javascript"></script>
    <script src="{{url('/')}}/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
    <script src="{{url('/')}}/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js"
            type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->

    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <script src="{{url('/')}}/assets/global/scripts/app.min.js" type="text/javascript"></script>
    <!-- END THEME GLOBAL SCRIPTS -->
    {{--    <script src="{{url('/')}}/assets/pages/scripts/components-select2.min.js" type="text/javascript"></script>--}}

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{url('/')}}/assets/pages/scripts/table-datatables-managed.min.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script src="{{url('/')}}/assets/js/schedules.js" type="text/javascript"></script>

@stop