routes/web.php
<?php

Route::get('/', function () {
    return redirect(admin_vw() . '/login');
});


Route::get('/reset-password', function () {
    return 'Reset password successfully';
});

Auth::routes(); //['verify' => true]

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::get('/user/verify_page', 'Auth\RegisterController@verifyingPage');


Route::group(['prefix' => 'admin'], function () {

    Route::get('login', 'Auth\Admin\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Auth\Admin\LoginController@loginAdmin')->name('admin.auth.login');


    //admin password reset routes
    //https://academy.muva.tech/blog/part-viii-admin-password-reset-in-our-multiple-authentication-system-for-laravel-5-4/
    Route::post('/password/email', 'Auth\Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\Admin\ResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

    Route::get('/', 'HomeController@index');
    Route::get('dashboard', 'HomeController@index')->name('admin.index');

    Route::group(['middleware' => 'auth:admin'], function () {

//
//        foreach (\App\Models\Permission::all() as $permission) {
//            if ($permission->type == 'get')
//                Route::get('/' . $permission->alias . '/' . $permission->name, ['middleware' => 'permission:' . $permission->name, 'uses' => $permission->controller_name . '@' . $permission->function_name]);
//            if ($permission->type == 'post')
//                Route::post('/' . $permission->alias . '/' . $permission->name, ['middleware' => 'permission:' . $permission->name, 'uses' => $permission->controller_name . '@' . $permission->function_name]);
//            if ($permission->type == 'put')
//                Route::put('/' . $permission->alias . '/' . $permission->name, ['middleware' => 'permission:' . $permission->name, 'uses' => $permission->controller_name . '@' . $permission->function_name]);
//            if ($permission->type == 'delete')
//                Route::delete('/' . $permission->alias . '/' . $permission->name, ['middleware' => 'permission:' . $permission->name, 'uses' => $permission->controller_name . '@' . $permission->function_name]);
//        }

        Route::get('users-home', 'HomeController@getUsers');

        Route::group(['prefix' => 'role'], function () {
//            Route::get('roles', 'RoleController@roles');
//            Route::get('add-role', 'RoleController@addRole');
//            Route::post('add-role', 'RoleController@postAddRole');
//            Route::get('edit-role/{id}', 'RoleController@editRole');
//            Route::put('edit-role/{id}', 'RoleController@putRole');
//            Route::delete('delete-role/{id}', 'RoleController@delete');
            Route::get('role-data', 'RoleController@roleData');
//            Route::get('addPermission', 'PermissionController@addPermission');
//            Route::get('add-permission-role/{role_id}', 'PermissionController@permissions');
//            Route::get('add-permission-role/{role_id}', 'PermissionController@addPermission');
//            Route::get('add-permission-role/{role_id}', 'PermissionController@addPermissionRole');

            Route::get('permission-role/{role_id}', 'PermissionController@getPermissionRole');
            Route::post('add-role-permissions/{role_id}', 'PermissionController@postAddRolePermissions');

        });

        Route::group(['prefix' => 'manage'], function () {
            Route::get('admins', 'Admin\AdminController@index')->name('admin.admins.index');
            Route::get('admin-data', 'Admin\AdminController@anyData');
            Route::get('admin/{id}/edit', 'Admin\AdminController@edit');
            Route::put('admin/{id}', 'Admin\AdminController@update');
            Route::get('admin/create', 'Admin\AdminController@create');
            Route::post('admin', 'Admin\AdminController@store');
            Route::delete('admin/{id}', 'Admin\AdminController@delete');
//            Route::post('admin/export', 'AdminController@export');
            Route::put('admin-activation', 'Admin\AdminController@adminActivate');

            Route::get('users', 'Admin\UserController@index')->name('admin.users.index');
            Route::get('user-data', 'Admin\UserController@anyData');
            Route::get('user-details/{id}', 'Admin\UserController@userDetails');
//            Route::put('verify-email', 'UserController@verifyEmail');
            Route::put('user-activation', 'Admin\UserController@userActive');
            Route::put('user-league', 'Admin\UserController@userHasLeague');
//            Route::post('user/export', 'UserController@export');

        });

        Route::resource('teams', 'Admin\TeamController');
        Route::group(['prefix' => 'team'], function () {
            Route::get('team-data', 'Admin\TeamController@anyData');
            Route::put('activation', 'Admin\TeamController@teamActivate');
        });

//////////Sport/////////////////////////////////
        Route::resource('sports', 'Admin\SportController');
        Route::post('sports/upload-media/{id}/', 'Admin\SportController@upload_media');
        Route::delete('sports/remove-media/{id}/', 'Admin\SportController@remove_media');

        Route::group(['prefix' => 'sport'], function () {
            Route::get('sports-data', 'Admin\SportController@anyData');
            Route::put('activation', 'Admin\SportController@activation');
            Route::post('/{id}', 'Admin\SportController@update');

        });
 /////////////////////////////League/////////////
        ///
         Route::resource('leagues', 'Admin\LeagueController');
        Route::group(['prefix' => 'league'], function () {
            Route::get('league-data', 'Admin\LeagueController@anyData');
            Route::put('activation', 'Admin\LeagueController@activation');

        });
///////////////////Constants///
        Route::get('constant', 'Admin\ConstantController@index')->name('constants.index');

        Route::group(['prefix' => 'constant'], function () {

            Route::resource('payments', 'Admin\PaymentController');
            Route::get('payment/payment-data', 'Admin\PaymentController@anyData');

            Route::resource('awards', 'Admin\AwardController');
            Route::get('award/award-data', 'Admin\AwardController@anyData');

            Route::resource('cities', 'Admin\CityController');
            Route::get('city/city-data', 'Admin\CityController@anyData');

            /////FacilityGround
            Route::resource('facilityGrounds', 'Admin\FacilityGroundController');
            Route::get('facilityGround/ground-data', 'Admin\FacilityGroundController@anyData');


            /////FacilitySize
            Route::resource('facilitySizes', 'Admin\FacilitySizeController');
            Route::get('facilitySize/size-data', 'Admin\FacilitySizeController@anyData');


//            Route::get('setting/settings', 'SettingController@getSettings');
            Route::get('setting/setting-data', 'SettingController@anyData');
//            Route::get('setting/{id}/edit', 'SettingController@edit');
//            Route::put('setting/{id}/edit', 'SettingController@update');
//            Route::get('setting/create', 'SettingController@create');
//            Route::post('setting/create', 'SettingController@store');
//            Route::post('setting/export', 'SettingController@export');
//            Route::delete('setting/{id}', 'SettingController@delete');

        });


//        Route::post('addPermission', 'PermissionController@postAddPermission');

        Route::post('logout', 'Auth\Admin\LoginController@logout')->name('admin.logout');

    });
});

resources/views/admin/layout/css.blade.php
<!--begin::Global Theme Styles -->
<link href="{{url('/')}}/assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css" />

<!--RTL version:<link href="assets/vendors/base/vendors.bundle.rtl.css" rel="stylesheet" type="text/css" />-->
<link href="{{url('/')}}/assets/demo/demo12/base/style.bundle.css" rel="stylesheet" type="text/css" />
<link href="{{url('/')}}/assets/demo/default/base/style.bundle.css" rel="stylesheet" type="text/css" />

<!--RTL version:<link href="assets/demo/demo12/base/style.bundle.rtl.css" rel="stylesheet" type="text/css" />-->

<!--end::Global Theme Styles -->

<!--begin::Page Vendors Styles -->
<link href="{{url('/')}}/assets/vendors/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" type="text/css" />

<!--RTL version:<link href="assets/vendors/custom/fullcalendar/fullcalendar.bundle.rtl.css" rel="stylesheet" type="text/css" />-->

<!--end::Page Vendors Styles -->
<link rel="shortcut icon" href="{{url('/')}}/assets/demo/demo12/media/img/logo/favicon.ico" />
<link rel="shortcut icon" href="{{url('/')}}/assets/demo/default/base/customStyle.css" />
<link rel="stylesheet" href="{{url('/')}}/assets/css/icon.css" />
<link rel="stylesheet" href="{{url('/')}}/assets/app/css/bootstrap-fileinput.css" />

<link href="{{url('/')}}/assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css" />
<link href="{{url('/')}}/assets/demo/demo12/base/style.bundle.css" rel="stylesheet" type="text/css" />
<!--begin::Web font -->

<link href="{{url('/')}}/assets/vendors/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
<!--end::Web font -->
<style>
    .btn.btn-icon.btn-circle {
        border-radius: 50%;
    }
    .btn.btn-icon {
        height: 3rem;
        width: 3rem;
    }
    .btn.btn-icon {
        /*display: -webkit-inline-box;*/
        display: -ms-inline-flexbox;
        display: inline-flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        padding: 0;
    }

    .img-circle{
        border-radius: 50%!important;
        height: 100px;
        width: 100px;
    }
</style>
@yield('css')

resources/views/admin/layout/footer.blade.php
<footer class="m-grid__item		m-footer ">
    <div class="m-container m-container--fluid m-container--full-height m-page__container">
        <div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
            <div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
							<span class="m-footer__copyright">
								2020 &copy; TeamUp
							</span>
            </div>
            <div class="m-stack__item m-stack__item--right m-stack__item--middle m-stack__item--first">
                <ul class="m-footer__nav m-nav m-nav--inline m--pull-right">
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">About</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Privacy</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">T&C</span>
                        </a>
                    </li>
          
                    <li class="m-nav__item m-nav__item">
                        <a href="#" class="m-nav__link" data-toggle="m-tooltip" title="Support Center" data-placement="left">
                            <i class="m-nav__link-icon flaticon-info m--icon-font-size-lg3"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/admin/layout/js.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
<!--begin::Global Theme Bundle -->
<script src="{{url('/')}}/js/jquery.min.js" type="text/javascript"></script>

{{--<script src="{{url('/')}}/assets/demo/demo12/base/scripts.bundle.js" type="text/javascript"></script>--}}
<script src="{{url('/')}}/assets/vendors/base/vendors.bundle.js" type="text/javascript"></script>
<script src="{{url('/')}}/assets/demo/default/base/scripts.bundle.js" type="text/javascript"></script>

<!--end::Global Theme Bundle -->

<!--begin::Page Vendors -->
<script src="{{url('/')}}/assets/vendors/custom/fullcalendar/fullcalendar.bundle.js" type="text/javascript"></script>

<!--end::Page Vendors -->

<!--begin::Page Scripts -->
<script src="{{url('/')}}/assets/app/js/dashboard.js" type="text/javascript"></script>
<script src="{{url('/')}}/assets/demo/demo12/custom/components/bootbox/bootbox.min.js" type="text/javascript"></script>
<script src="{{url('/')}}/assets/demo/default/custom/crud/forms/widgets/dropzone.js" type="text/javascript"></script>

<!--end::Page Scripts -->
<script>
    WebFont.load({
        google: {"families":["Poppins:300,400,500,600,700","Roboto:300,400,500,600,700"]},
        active: function() {
            sessionStorage.fonts = true;
        }
    });
</script>
<script>
    var baseURL = '{{url(admin_vw())}}';
    var baseAssets = '{{url('assets')}}';

    $(window).keydown(function(event){
        if(event.keyCode == 13) {
            event.preventDefault();
            return false;
        }
    });
</script>
@yield('js')

<script>
    var csrf_token = $('meta[name="csrf-token"]').attr('content');
</script>

{{--<!--begin::Page Scripts -->--}}

<!--begin::Page Vendors -->

<!--end::Page Vendors -->

<script src="{{url('/')}}/assets/demo/default/base/scripts.bundle.js" type="text/javascript"></script>
<script src="{{url('/')}}/assets/vendors/custom/datatables/datatables.bundle.js" type="text/javascript"></script>
<script src="{{url('/')}}/assets/demo/default/custom/crud/datatables/extensions/buttons.js" type="text/javascript"></script>
<!--begin::Page Vendors -->
<script src="{{url('/')}}/assets/vendors/custom/fullcalendar/fullcalendar.bundle.js" type="text/javascript"></script>
<!--end::Page Vendors -->
<script src="{{url('/')}}/assets/app/js/customjs.js" type="text/javascript"></script>

<!--end::Global Theme Bundle -->

<!--begin::Page Vendors -->
<script src="{{url('/')}}/assets/vendors/custom/fullcalendar/fullcalendar.bundle.js" type="text/javascript"></script>

<!--end::Page Vendors -->

<!--begin::Page Scripts -->
<script src="{{url('/')}}/assets/app/js/dashboard.js" type="text/javascript"></script>
<script src="{{url('/')}}/assets/app/js/bootstrap-fileinput.js" type="text/javascript"></script>
<!--end::Page Scripts -->

<!-- begin::Page Loader -->
<script>
    $(window).on('load', function () {
        $('body').removeClass('m-page--loading');
    });
</script>
<script>
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "positionClass": "toast-top-right",
        "onclick": null,
        "showDuration": "1000",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
</script>
<script>

    // var myDropzone;
    // Dropzone.autoDiscover = false;
    // myDropzone = new Dropzone("#m-dropzone-one", {
    //     autoProcessQueue: false
    // });

</script>

{{--<script type="text/javascript">function add_chatinline(){var hccid=96140841;var nt=document.createElement("script");nt.async=true;nt.src="https://mylivechat.com/chatinline.aspx?hccid="+hccid;var ct=document.getElementsByTagName("script")[0];ct.parentNode.insertBefore(nt,ct);}--}}
    {{--add_chatinline(); </script>--}}
@stack('js')

resources/views/admin/layout/sidebar.blade.php
<div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-dark ">

    <!-- BEGIN: Aside Menu -->
    <div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark " m-menu-vertical="1" m-menu-scrollable="0" m-menu-dropdown-timeout="500">
        <ul class="m-menu__nav ">
            <li class="m-menu__section m-menu__section--first">
                <h4 class="m-menu__section-text">Departments</h4>
                <i class="m-menu__section-icon flaticon-more-v2"></i>
            </li>
            <li class="m-menu__item   {{request()->is(Request::segment(1) . '/dashboard')? 'm-menu__item--active' : ''}}" aria-haspopup="true"><a href="{{route('admin.index')}}" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-line-graph"></i><span class="m-menu__link-text">Dashboard</span></a></li>
            <!--	<li class="m-menu__item  m-menu__item--submenu" aria-haspopup="true" m-menu-submenu-toggle="hover"><a href="javascript:;" class="m-menu__link m-menu__toggle"><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-layers"></i><span
                         class="m-menu__link-text">Resources</span><i class="m-menu__ver-arrow la la-angle-right"></i></a>
                    <div class="m-menu__submenu "><span class="m-menu__arrow"></span>
                        <ul class="m-menu__subnav">
                            <li class="m-menu__item  m-menu__item--parent" aria-haspopup="true"><span class="m-menu__link"><span class="m-menu__item-here"></span><span class="m-menu__link-text">Resources</span></span></li>
                            <li class="m-menu__item " aria-haspopup="true"><a href="inner.html" class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">Timesheet</span></a></li>
                            <li class="m-menu__item " aria-haspopup="true" m-menu-link-redirect="1"><a href="inner.html" class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">Payroll</span></a></li>
                            <li class="m-menu__item " aria-haspopup="true" m-menu-link-redirect="1"><a href="inner.html" class="m-menu__link "><i class="m-menu__link-bullet m-menu__link-bullet--dot"><span></span></i><span class="m-menu__link-text">Contacts</span></a></li>
                        </ul>
                    </div>
                </li>-->

            <li class="m-menu__item {{Request::segment(3) == 'admins' ? 'm-menu__item--active' : ''}}" aria-haspopup="true" m-menu-link-redirect="1"><a href="{{route('admin.admins.index')}}" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-graphic-1"></i><span class="m-menu__link-text">system
								Management</span></a></li>
            <li class="m-menu__item {{Request::segment(3) == 'users'? 'm-menu__item--active' : ''}}" aria-haspopup="true" m-menu-link-redirect="1"><a href="{{route('admin.users.index')}}" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-suitcase"></i><span class="m-menu__link-text">Users</span></a></li>
            <li class="m-menu__item {{Request::segment(2) == 'team'? 'm-menu__item--active' : ''}}" aria-haspopup="true" m-menu-link-redirect="1"><a href="{{route('teams.index')}}" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-light"></i><span class="m-menu__link-text">Teams</span></a></li>
            <li class="m-menu__item " aria-haspopup="true" m-menu-link-redirect="1"><a href="{{route('leagues.index')}}" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-share"></i><span class="m-menu__link-text">Leagues</span></a></li>
            <li class="m-menu__item " aria-haspopup="true" m-menu-link-redirect="1"><a href="{{route('sports.index')}}" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-share"></i><span class="m-menu__link-text">Sports</span></a></li>
            <li class="m-menu__item " aria-haspopup="true" m-menu-link-redirect="1"><a href="#" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-lifebuoy"></i><span class="m-menu__link-text">Posts</span></a></li>
            <li class="m-menu__item {{Request::segment(2) == 'constant'? 'm-menu__item--active' : ''}}" aria-haspopup="true" m-menu-link-redirect="1"><a href="{{route('constants.index')}}" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-settings"></i><span class="m-menu__link-text">Constants</span></a></li>
            <li class="m-menu__item " aria-haspopup="true" m-menu-link-redirect="1"><a href="#" class="m-menu__link "><span class="m-menu__item-here"></span><i class="m-menu__link-icon flaticon-settings"></i><span class="m-menu__link-text">Settings</span></a></li>
        </ul>
    </div>

    <!-- END: Aside Menu -->
</div>